"""initial migration

Revision ID: 28d4f2581f59
Revises: 190163627111
Create Date: 2017-09-27 22:39:04.761471

"""

# revision identifiers, used by Alembic.
revision = '28d4f2581f59'
down_revision = '190163627111'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digit_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ratio', sa.String(length=64), nullable=True),
    sa.Column('mapper', sa.String(length=64), nullable=True),
    sa.Column('command', sa.String(length=64), nullable=True),
    sa.Column('cmd_param', sa.String(length=64), nullable=True),
    sa.Column('cmd_length', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digit_info')
    # ### end Alembic commands ###
